spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/store"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/store"
server:
  port: 8081